### ISSUE TITLE
Missing my CppCon presentation :)

### ISSUE THREAD

**Issue by ned14** [CppCon/CppCon2015#5]
PDF is downloadable from https://drive.google.com/file/d/0B5QDPUNHLpKMNDNDYnIyTDJZblU/view?usp=sharing

**Comment by sdutoit** [comment]
Added - not sure how that slipped by the initial round of additions! Thanks!

**Comment by sdutoit** [comment]
Turns out all of the tutorials and workshops were missing from the index - your presentation was [there](https://github.com/CppCon/CppCon2015/tree/master/Tutorials/Racing%20the%20Filesystem), just hidden away. Tutorials are now listed in the [index](https://github.com/CppCon/CppCon2015).
